// External dependencies
import { CgSmartHomeRefrigerator, CgMouse } from "react-icons/cg";
import {
  MdTablet,
  MdInventory,
  MdBuild,
  MdPhoneIphone,
  MdLaptop,
  MdKitchen,
  MdHome,
  MdEventSeat,
  MdCoffeeMaker,
  MdSpeaker,
  MdWbIncandescent,
} from "react-icons/md";
import { TbAirConditioning } from "react-icons/tb";

// Internal dependencies
import { Product } from "./columns";

const productsData: Product[] = [
  {
    id: "1",
    name: "Refrigerator",
    supplier: "HomeGoods Co.",
    sku: "RF404",
    category: "Home Appliances",
    status: "Inactive",
    quantityInStock: 8,
    price: 799.99,
    icon: CgSmartHomeRefrigerator,
  },
  {
    id: "2",
    name: "Tablet",
    supplier: "TechWorld",
    sku: "TB505",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 60,
    price: 199.99,
    icon: MdTablet,
  },
  {
    id: "3",
    name: "Screwdriver",
    supplier: "ToolSupplier Inc.",
    sku: "SD123",
    category: "Others",
    status: "Draft",
    quantityInStock: 50,
    price: 12.99,
    icon: MdBuild,
  },
  {
    id: "4",
    name: "Hammer",
    supplier: "ToolSupplier Inc.",
    sku: "HM456",
    category: "Others",
    status: "Published",
    quantityInStock: 30,
    price: 15.5,
    icon: MdInventory,
  },
  {
    id: "5",
    name: "Smartphone",
    supplier: "TechWorld",
    sku: "SP789",
    category: "Electronics",
    status: "Published",
    quantityInStock: 100,
    price: 499.99,
    icon: MdPhoneIphone,
  },
  {
    id: "6",
    name: "Laptop",
    supplier: "TechWorld",
    sku: "LT101",
    category: "Electronics",
    status: "Inactive",
    quantityInStock: 25,
    price: 899.99,
    icon: MdLaptop,
  },
  {
    id: "7",
    name: "Microwave Oven",
    supplier: "HomeGoods Co.",
    sku: "MO202",
    category: "Furniture",
    status: "Draft",
    quantityInStock: 15,
    price: 120,
    icon: MdKitchen,
  },
  {
    id: "8",
    name: "Washing Machine",
    supplier: "HomeGoods Co.",
    sku: "WM303",
    category: "Home Decor",
    status: "Published",
    quantityInStock: 10,
    price: 450,
    icon: MdHome,
  },
  {
    id: "9",
    name: "Gaming Mouse",
    supplier: "GadgetKing",
    sku: "GM001",
    category: "Electronics",
    status: "Published",
    quantityInStock: 45,
    price: 39.99,
    icon: CgMouse,
  },
  {
    id: "10",
    name: "Office Chair",
    supplier: "FurniPro",
    sku: "OC002",
    category: "Furniture",
    status: "Inactive",
    quantityInStock: 12,
    price: 149.99,
    icon: MdEventSeat,
  },
  {
    id: "11",
    name: "Coffee Maker",
    supplier: "KitchenEssentials",
    sku: "CM101",
    category: "Home Appliances",
    status: "Draft",
    quantityInStock: 20,
    price: 99.99,
    icon: MdCoffeeMaker,
  },
  {
    id: "12",
    name: "Air Conditioner",
    supplier: "HomeGoods Co.",
    sku: "AC202",
    category: "Home Appliances",
    status: "Published",
    quantityInStock: 5,
    price: 599.99,
    icon: TbAirConditioning,
  },
  {
    id: "13",
    name: "Bluetooth Speaker",
    supplier: "TechWorld",
    sku: "BS404",
    category: "Electronics",
    status: "Inactive",
    quantityInStock: 50,
    price: 79.99,
    icon: MdSpeaker,
  },
  {
    id: "14",
    name: "Desk Lamp",
    supplier: "HomeDecorCo.",
    sku: "DL505",
    category: "Home Decor",
    status: "Draft",
    quantityInStock: 18,
    price: 29.99,
    icon: MdWbIncandescent,
  },
];

export default productsData;
